# amper-project/justfile

set fallback := true
set unstable := true

import "../just/projects.just"

[private]
default:
  @just --list

# Run the project
[group("Run")]
run:
    ./amper run

# update amper
[group("Misc")]
update-amper:
    ./amper update -c
