# gradle-project/justfile

set fallback := true
set export := true
set unstable := true

import "../just/projects.just"

[private]
gradle-default:
    @just --list

# Clean and assemble the project
[group("build")]
clean-assemble:
    ./gradlew clean assemble
